"""added priority

Revision ID: 0927f2f0e004
Revises: e1bd420115cc
Create Date: 2019-11-16 14:38:01.784000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0927f2f0e004'
down_revision = 'e1bd420115cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'priority')
    # ### end Alembic commands ###
