"""notes table

Revision ID: d4bfe7b7581a
Revises: d6ad3a97fba9
Create Date: 2019-10-26 12:39:08.910402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bfe7b7581a'
down_revision = 'd6ad3a97fba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_due_date'), 'note', ['due_date'], unique=False)
    op.create_index(op.f('ix_note_timestamp'), 'note', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_timestamp'), table_name='note')
    op.drop_index(op.f('ix_note_due_date'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
